<?php
// Continent → [ ISO2 => Hungarian name ]
return [
  'Európa' => [
    'HU' => 'Magyarország',
    'AT' => 'Ausztria',
    'DE' => 'Németország',
    'RO' => 'Románia',
    'SK' => 'Szlovákia',
    'SI' => 'Szlovénia',
    'HR' => 'Horvátország',
    'CZ' => 'Csehország',
    'PL' => 'Lengyelország',
    'GB' => 'Egyesült Királyság',
    'IE' => 'Írország',
    'FR' => 'Franciaország',
    'ES' => 'Spanyolország',
    'PT' => 'Portugália',
    'IT' => 'Olaszország',
    'NL' => 'Hollandia',
    'BE' => 'Belgium',
    'LU' => 'Luxemburg',
    'DK' => 'Dánia',
    'SE' => 'Svédország',
    'NO' => 'Norvégia',
    'FI' => 'Finnország',
    'EE' => 'Észtország',
    'LV' => 'Lettország',
    'LT' => 'Litvánia',
    'GR' => 'Görögország',
    'BG' => 'Bulgária',
    'CH' => 'Svájc',
    'IS' => 'Izland',
    'UA' => 'Ukrajna',
    'RU' => 'Oroszország',
  ],

  'Észak-Amerika' => [
    'US' => 'Egyesült Államok',
    'CA' => 'Kanada',
    'MX' => 'Mexikó',
  ],

  'Dél-Amerika' => [
    'BR' => 'Brazília',
    'AR' => 'Argentína',
    'CL' => 'Chile',
  ],

  'Ázsia' => [
    'TR' => 'Törökország',
    'IL' => 'Izrael',
    'AE' => 'Egyesült Arab Emírségek',
    'SA' => 'Szaúd-Arábia',
    'QA' => 'Katar',
    'JP' => 'Japán',
    'KR' => 'Dél-Korea',
    'CN' => 'Kína',
    'TW' => 'Tajvan',
    'HK' => 'Hongkong',
    'SG' => 'Szingapúr',
    'MY' => 'Malajzia',
    'TH' => 'Thaiföld',
    'VN' => 'Vietnam',
    'ID' => 'Indonézia',
    'PH' => 'Fülöp-szigetek',
    'IN' => 'India',
    'PK' => 'Pakisztán',
    'BD' => 'Banglades',
  ],

  'Óceánia' => [
    'AU' => 'Ausztrália',
    'NZ' => 'Új-Zéland',
  ],

  'Afrika' => [
    'EG' => 'Egyiptom',
    'ZA' => 'Dél-afrikai Köztársaság',
    'NG' => 'Nigéria',
    'KE' => 'Kenya',
    'MA' => 'Marokkó',
  ],
];
